---
title: "Prepare supplementary table of test scores by state"
output: html_document 
---

#Load packages and file locations
```{r}
rm(list=ls())

# Declare root directory, folder locations, local file locations, objects, and functions
project.folder = paste0(print(here::here()),'/')
source(paste0(project.folder,'create_folder_structure.R'))
source(paste0(file.locations.folder,'file_locations.R'))
source(paste0(objects.folder,'objects.R'))
source(paste0(functions.folder,'functions.R'))

library(tidyverse)
library(Hmisc)
library(dplyr)
```

#Load datasets
```{r}
#Load datasets
math.DID = readRDS(paste0(prepared.math.DID.folder, "math_DID_hurricanes_lagged.rds"))
rla.DID = readRDS(paste0(prepared.rla.DID.folder, "rla_DID_hurricanes_lagged.rds"))
```

#Which states ever had exposure to hurricanes?
```{r}
states_to_include = math.DID %>% filter(et==1) %>% pull(state) %>% unique()
states_to_include = as.character(states_to_include)
```

#Filter for states which ever had exposure to hurricanes
```{r}
math.DID = math.DID %>% 
  filter(state%in%states_to_include) %>% 
  mutate(state=as.numeric(as.character(state)))
rla.DID = rla.DID %>% 
  filter(state%in%states_to_include) %>% 
  mutate(state=as.numeric(as.character(state)))
```

#Describe the distribution of math scores in 2009 for grade 3
```{r}
math.DID %>% dplyr::filter(year == 2018, grade == 8, state == 48) %>% dplyr::select(gcs_mn_all) %>% describe()
```

#Describe the distribution of RLA scores in 2009 for grade 3
```{r}
rla.DID %>% dplyr::filter(year == 2018, grade == 8, state == 48) %>% dplyr::select(gcs_mn_all) %>% describe()
```

#Florida 12
#Louisiana 22
#New Jersey 34
#North Carolina 37
#South Carolina 45
#Texas 48

