```{r}
rm(list=ls())
```

# Declare root directory, folder locations, local file locations, objects, and functions
```{r}
project.folder = paste0(print(here::here()),'/')
source(paste0(project.folder,'create_folder_structure.R'))
source(paste0(file.locations.folder,'file_locations.R'))
source(paste0(objects.folder,'objects.R'))
source(paste0(functions.folder,'functions.R'))
```

#Load exposure data into environment
```{r}
library(tidyverse)
library(knitr)
exposure.data <- readRDS('~/Git/tropical_cyclones_educational_attainment_2022/data/tc_exposure/github_processed/tc_annual_county_exposure_treatment_once_2008_2019.rds')
```

#Rename fips to sedacounty, generate state code, and change to numeric variable
```{r}
exposure.data <- exposure.data %>% rename(sedacounty = fips) %>% mutate(state=substr(sedacounty,1,2))
exposure.data$sedacounty <- as.numeric(exposure.data$sedacounty)
```

#Merge hurricane data with processed math and rla dataframes
```{r}
processed.math <- readRDS('~/Git/tropical_cyclones_educational_attainment_2022/data/prepared_data/prepared_math/processed_math.rds')
processed.rla <- readRDS('~/Git/tropical_cyclones_educational_attainment_2022/data/prepared_data/prepared_rla/processed_rla.rds')
```

```{r}
math.DID <- full_join(processed.math, exposure.data, by = c('sedacounty', 'year')) %>%
  distinct() %>% relocate(state) %>% filter((is.na(subject)!=TRUE))
rla.DID <- full_join(processed.rla, exposure.data, by = c('sedacounty', 'year')) %>%
  distinct() %>% relocate(state) %>% filter((is.na(subject)!=TRUE))
```

#Save DID data in the appropriate folder 
```{r}
saveRDS(math.DID, paste0(prepared.math.DID.folder, "math_DID_cyclones_once.rds"))
saveRDS(rla.DID, paste0(prepared.rla.DID.folder, "rla_DID_cyclones_once.rds"))
```


